language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    - sys-img-armeabi-v7a-android-24
    - sys-img-x86-android-21
  licenses:
    - 'android-sdk-license-5be876d5'
    - 'android-sdk-license-c81a61d9'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
